name: Terraform Plan

on:
  push:
    branches:
      - main   # or your branch you treat as “env”
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    environment: tfplan   # this environment may have no approval, so plan runs automatically
    defaults:
      run:
        working-directory: ./   # adjust to your Terraform folder current

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.SPN_APP_ID }}  
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ vars.SPN_APP_ID }}
          ARM_TENANT_ID: ${{ vars.TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}

      - name: Terraform Plan
        id: tfplan
        run: terraform plan -out=tfplan
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ vars.SPN_APP_ID }}
          ARM_TENANT_ID: ${{ vars.TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
